name: nylo_framework
description: Micro-framework for Flutter that's built to simplify app development for Flutter projects.
version: 2.1.1
homepage: https://nylo.dev
repository: https://github.com/nylo-core/framework
issue_tracker: https://github.com/nylo-core/framework/issues
documentation: https://github.com/nylo-core/framework

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  flutter_dotenv: ^5.0.2
  nylo_support: ^2.2.1
  flutter_launcher_icons: ^0.9.2
  args: ^2.3.0
  theme_provider: ^0.5.0
  recase: ^4.0.0
  flutter:
    sdk: flutter
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

